"use client";

import { useState, useEffect, useCallback } from "react";
import {
  BoardContainer,
  Board,
  LoadingContainer,
  Spinner,
} from "./KanbanBoard.styles";
import { Column } from "./Column/Column";
import { Toolbar } from "./shared/Toolbar";
import { TaskStatus, TaskPriority, Task, emptyTaskColumns } from "./types";
import {
  fetchTaskBoardNameMap,
  loadTaskBoardContent,
} from "./shared/dataLoaders";
import { handleSingleBoardTaskStatusChange } from "./shared/taskStatusHandlers";
import TaskView from "../TaskView/TaskView";
import {
  useTaskBoardState,
  updateTaskInColumns,
} from "@/hooks/useTaskBoardState";

interface SingleKanbanBoardProps {
  boardName: string;
  workspaceTitle: string;
  taskBoardNameMap?: Record<string, string>;
}

export function SingleKanbanBoard({
  boardName,
  workspaceTitle,
  taskBoardNameMap = {},
}: SingleKanbanBoardProps) {
  const [tasks, setTasks] =
    useState<Record<TaskStatus, Task[]>>(emptyTaskColumns);
  const [isLoading, setIsLoading] = useState(true);
  const [taskBoardId, setTaskBoardId] = useState<string | null>(null);

  const {
    selectedTask,
    parentTask,
    setSelectedTask,
    handleTaskClick,
    handleCloseModal,
    handleSubtaskClick,
  } = useTaskBoardState();

  useEffect(() => {
    const fetchTasks = async () => {
      setIsLoading(true);
      try {
        const taskBoardNamesMap =
          Object.keys(taskBoardNameMap).length > 0
            ? taskBoardNameMap
            : await fetchTaskBoardNameMap();
        const foundTaskBoardId = findTaskBoardId(taskBoardNamesMap, boardName);

        setTaskBoardId(foundTaskBoardId);

        await loadTaskBoardContent({
          boardName,
          taskBoardNamesMap,
          setTasks,
        });
      } catch (error) {
        console.error("Failed to fetch tasks:", error);
        setTasks(emptyTaskColumns);
      } finally {
        setIsLoading(false);
      }
    };

    fetchTasks();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [boardName]);

  const handleTaskStatusChange = useCallback(
    async (taskId: string, newStatus: TaskStatus, targetIndex?: number) => {
      await handleSingleBoardTaskStatusChange(
        tasks,
        setTasks,
        taskId,
        newStatus,
        targetIndex,
      );
    },
    [tasks],
  );

  const handleTaskUpdate = useCallback(
    (updatedTask: Task) => {
      setTasks((prevTasks) => updateTaskInColumns(prevTasks, updatedTask));
      if (selectedTask?.id === updatedTask.id) {
        setSelectedTask(updatedTask);
      }
    },
    [selectedTask, setSelectedTask],
  );

  const handleCreateTask = useCallback(() => {
    if (!taskBoardId) {
      console.error("Cannot create task: taskBoardId not found");
      return;
    }
    // Create a new task template
    const newTask: Task = {
      id: "", // Will be generated by API
      taskBoardId,
      summary: "",
      description: "",
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
    };
    setSelectedTask(newTask);
  }, [taskBoardId, setSelectedTask]);

  const handleTaskCreated = useCallback(
    async (createdTask: Task) => {
      // Refresh tasks
      try {
        const taskBoardNamesMap =
          Object.keys(taskBoardNameMap).length > 0
            ? taskBoardNameMap
            : await fetchTaskBoardNameMap();
        await loadTaskBoardContent({
          boardName,
          taskBoardNamesMap,
          setTasks,
        });
        // Close modal and select the new task
        setSelectedTask(createdTask);
      } catch (error) {
        console.error("Failed to refresh tasks after creation:", error);
      }
    },
    [boardName, taskBoardNameMap, setSelectedTask],
  );

  return (
    <>
      <BoardContainer>
        <Toolbar
          workspaceTitle={workspaceTitle}
          onCreateTask={handleCreateTask}
        />

        <Board>
          {isLoading ? (
            <LoadingContainer>
              <Spinner />
            </LoadingContainer>
          ) : (
            <>
              <Column
                tasks={tasks[TaskStatus.TODO]}
                status={TaskStatus.TODO}
                onTaskDrop={handleTaskStatusChange}
                onTaskClick={handleTaskClick}
              />
              <Column
                tasks={tasks[TaskStatus.IN_PROGRESS]}
                status={TaskStatus.IN_PROGRESS}
                onTaskDrop={handleTaskStatusChange}
                onTaskClick={handleTaskClick}
              />
              <Column
                tasks={tasks[TaskStatus.DONE]}
                status={TaskStatus.DONE}
                onTaskDrop={handleTaskStatusChange}
                onTaskClick={handleTaskClick}
              />
            </>
          )}
        </Board>
      </BoardContainer>
      <TaskView
        task={selectedTask}
        parentTask={parentTask}
        workspaceTitle={workspaceTitle}
        onClose={handleCloseModal}
        onTaskUpdate={handleTaskUpdate}
        onSubtaskClick={handleSubtaskClick}
        onTaskCreated={handleTaskCreated}
      />
    </>
  );
}

function findTaskBoardId(
  taskBoardNamesMap: Record<string, string>,
  boardName: string,
): string | null {
  const targetEntry = Object.entries(taskBoardNamesMap).find(
    ([, name]) => name === boardName,
  );
  return targetEntry ? targetEntry[0] : null;
}
