// Re-export Better Auth generated schema so we don't duplicate table definitions
// Path from src/db/schema.ts to apps/api/auth-schema.ts
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - this file is generated by the Better Auth CLI
import { users as authUsers } from '../../auth-schema';
export const users = authUsers;

export type SelectUser = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
