export enum Route {
  LOGIN = "/login",
  AUTH_ERROR = "/auth/error",
  FORBIDDEN = "/forbidden",
  AUTH = "/auth",
  OVERVIEW = "/overview",
  CALENDAR = "/calendar",
  CALENDAR_EVENTS = "/calendar/events",
  TASKS = "/tasks",
  TASK_BOARDS = "/task-boards",
  FOLDERS = "/folders",
  LABELS = "/labels",
  STATS = "/stats",
  ANALYTICS = "/analytics",
  SETTINGS = "/settings",
}
